### ISSUE TITLE
Just a question not an issue

### ISSUE THREAD

**Issue by yakomisar** [gmr458/vscode_modern_theme.nvim#9]
Hi, do you have any plans to create a gruvbox theme based on the current themes you have (vscode,cold...) ?

**Comment by gmr458** [comment]
not really, but what about the other gruvbox themes that already exist?

**Comment by yakomisar** [comment]
The existing themes are quite slow. Furthermore, the codebase for different color schemes can be consolidated into a theme switcher.

**Comment by gmr458** [comment]
[gruvbox](https://github.com/ellisonleao/gruvbox.nvim) gruvbox takes between 9 and 10 ms to load on my machine
